Update cd-pipeline.yml

diff --git a/.github/workflows/cd-pipeline.yml b/.github/workflows/cd-pipeline.yml
--- a/.github/workflows/cd-pipeline.yml
+++ b/.github/workflows/cd-pipeline.yml
@@ -12,6 +12,9 @@ jobs:
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
 
     steps:
+      - name: Log Execution
+        run: echo "Deploy job is starting..."
+
       - name: Trigger Log
         run: |
           echo "Workflow triggered by: workflow_run on workflow '${{ github.event.workflow_run.name }}'"
@@ -21,6 +24,13 @@ jobs:
         run: |
           echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
 
+      - name: Log Trigger Event
+        run: |
+          echo "Event Name: ${{ github.event_name }}"
+          echo "Ref: ${{ github.ref }}"
+          echo "Workflow Name: ${{ github.event.workflow_run.name }}"
+          echo "Workflow Conclusion: ${{ github.event.workflow_run.conclusion }}"
+
       - name: Deploy to Render
         run: |
           response=$(curl -s -o /dev/null -w "%{http_code}" -X POST https://api.render.com/v1/deploy/${{ secrets.RENDER_SERVICE_ID }} \
@@ -29,4 +39,7 @@ jobs:
           -d '{"serviceId":"${{ secrets.RENDER_SERVICE_ID }}"}')
 
           if [ "$response" -ne 200 ]; then
-            echo "De
+            echo "Deployment failed with response code $response"
+            exit 1
+          fi
+          echo "Deployment was successful!"
